title: Jack Waudby
email: j.waudby2@ncl.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
    I'm Jack Waudby, a Computer Science PhD Student at Newcastle University.
    Distributed database systems are my thing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: waudberry_7
github_username:  jackwaudby
linkedin_username: jack-waudby

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

header_pages:
    - publications.md
